// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "52d7d447-10c4-4b92-acb3-6051d83c1755";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)


CloudTemperatureSensor processor_Temp;
CloudElectricPotention voltage;
int rssi;
CloudTemperatureSensor water_Temp;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(processor_Temp, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(voltage, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(rssi, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(water_Temp, READ, 1 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
